apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-demo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/PetrMc/k8s-manifest-registry
    path: argocd/backstage/clusters/portal-petr-aoa-0/apps/react-demo-app/app
    targetRevision: main
    directory:
      recurse: true
      exclude: '{*catalog-info.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 1m0s